services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: vepramim-frontend:production
    container_name: vepramim-frontend
    restart: unless-stopped
    dns:
      - 172.30.0.254
      - 172.30.0.252
    environment:
      - NODE_ENV=production
      - PORT=3002
    ports:
      - "3002:3002"
    healthcheck:
      test: ["CMD", "wget", "--spider", "http://localhost:3002"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s 