services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: vepramim-frontend:production
    container_name: vepramim-frontend
    restart: unless-stopped
    environment:
      - NODE_ENV=production
      - PORT=3000
    ports:
      - "3000:3000"
    healthcheck:
      test: ["CMD", "wget", "--spider", "http://localhost:3000"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s 